name: Zip Repository on Push

on:
  push:
    branches:
      - main

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip directory
        run: zip -r Prsn.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Prsn-zip
          path: Prsn.zip
