name: Zip Resource Pack

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Zip Resource Pack into Prsn.zip
        run: |
          cd "Resource Pack"
          zip -r ../Prsn.zip ./*

      - name: Commit and push Prsn.zip
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ./Prsn.zip
          git commit -m "Update Prsn.zip"
          git push
        continue-on-error: true
