name: Zip Resource Pack Folder

on:
  push:
    branches: [main]  # Change to your default branch if needed
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  zip-resource-pack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Automatically zip resource pack
        run: |
          mkdir -p output
          zip -r output/Resource-Pack.zip "Resource Pack"

      - name: Commit ZIP file to repository
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          mv output/Resource-Pack.zip ./Prsn.zip

          # Prevent commit loop
          if [ -n "$(git status --porcelain)" ]; then
            git add -f Resource-Pack.zip
            git commit -m "Auto-zipped 'Resource Pack' folder"
            git push
          else
            echo "No changes to commit."
          fi
